# Make sure to check the documentation at http://goreleaser.com

before:
  hooks:
    - go mod tidy

builds:
  - binary: gromit
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
    ldflags:
      - -X github.com/TykTechnologies/gromit/util.version={{.Version}}
      - -X github.com/TykTechnologies/gromit/util.commit={{.Commit}}
      - -X github.com/TykTechnologies/gromit/util.buildDate={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

dockers:
  - image_templates:
      - "tykio/gromit:latest"
      - "tykio/gromit:{{.Tag}}"
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^utils:'
    - (?i)typo
    - 'Merge (pull request|branch)'
    - '\[CI\]'
    - '(?i)\[Buddy\]'
    - 'cherry picked'
    - '^rel-eng:'
    - '^minor:'

release:
  github:
    owner: TykTechnologies
    name: gromit
  discussion_category_name: General
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
