# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
      
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64

archives:
- replacements:
    linux: Linux
    386: i386
    amd64: x86_64

changelog:
  sort: asc
  filters:
    exclude:
    - '^utils:'
    - (?i)typo
    - (?i)fixup
