# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go get github.com/GeertJohan/go.rice/rice
    - rice -v embed-go -i ./terraform -i ./confgen
      
builds:
  -
    binary: gromit
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    ldflags:
      - -X github.com/TykTechnologies/gromit/util.version={{.Version}}
      - -X github.com/TykTechnologies/gromit/util.commit={{.Commit}}
      - -X github.com/TykTechnologies/gromit/util.buildDate={{.Date}}

archives:
- replacements:
    linux: Linux
    386: i386
    amd64: x86_64

dockers:
  -
    binaries:
      - gromit
    image_templates:
      - "tykio/gromit:latest"
      - "tykio/gromit:{{.Tag}}"
      
changelog:
  sort: asc
  filters:
    exclude:
    - '^utils:'
    - (?i)typo
    - (?i)fixup
