# Make sure to check the documentation at http://goreleaser.com

builds:
  - binary: gromit
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    ldflags:
      - -X github.com/TykTechnologies/gromit/util.version={{.Version}}
      - -X github.com/TykTechnologies/gromit/util.commit={{.Commit}}
      - -X github.com/TykTechnologies/gromit/util.buildDate={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      pre: go generate ./confgen ./devenv

archives:
- replacements:
    linux: Linux

dockers:
  - image_templates:
      - "tykio/gromit:latest"
      - "tykio/gromit:{{.Tag}}"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^utils:'
    - (?i)typo
    - (?i)fixup
