# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go get github.com/GeertJohan/go.rice
    - go get github.com/GeertJohan/go.rice/rice
      
builds:
  -
    binary: gromit
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    ldflags:
      - -X util.version={{ .Version }}
      - -X util.commit={{ .Commit }}
      - -X util.buildDate={{ .Date }}
    hooks:
      pre: rice embed-go -i ./terraform -i ./confgen

archives:
- replacements:
    linux: Linux
    386: i386
    amd64: x86_64

dockers:
  -
    binaries:
      - gromit
    image_templates:
      - "TykTechnologies/gromit:latest"
      - "TykTechnologies/gromit:{{ .Tag }}"
      
changelog:
  sort: asc
  filters:
    exclude:
    - '^utils:'
    - (?i)typo
    - (?i)fixup
