name: UI Regresion Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - 'tests/ui/**'
  push:
    branches:
      - master
      - release-*
    paths:
      - 'tests/ui/**'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
{{ $test := "ui" }}
  test-controller-{{ $test }}:
    runs-on: ubuntu-latest
    container: tykio/gromit:v1.8
    outputs:
      gd_tag: {{`${{ steps.params.outputs.gd_tag }}`}}
      versions: {{`${{ steps.params.outputs.versions }}`}}
    steps:
      - name: set params
        id: params
        env:
          REPO: {{`${{ github.repository }}`}}
          # Cover pull_request_target too
          BASE_REF: {{`${{startsWith(github.event_name, 'pull_request') && github.base_ref || github.ref}}`}}
          TAGS: {{`${{ github.sha }}`}}
          IS_PR: {{`${{startsWith(github.event_name, 'pull_request') && 'yes' }}`}}
          IS_TAG: {{`${{startsWith(github.ref, 'refs/tags') && 'yes' }}`}}
          JOB: {{ $test }}
        run: gromit policy controller --loglevel debug | tee -a "$GITHUB_OUTPUT"
  {{ $test }}-tests:
    runs-on: ubuntu-latest
    needs: test-controller-{{ $test }}
    env:
      METADATA_REPORT_PATH: /tmp/metadata.toml
      {{ if eq $test "ui" }}
      XUNIT_REPORT_PATH: {{`${{ github.workspace }}`}}/tyk-analytics/tests/ui/playwright-report/results.xml
      {{- end }}
      {{ if eq $test "api" }}
      XUNIT_REPORT_PATH: {{`${{ github.workspace }}`}}/reports/pytest-report.xml
      {{- end }}     
    permissions:
      id-token: write # This is required for requesting the Github JWT
      contents: read # This is required for actions/checkout
    strategy:
      fail-fast: false
      matrix:		
        conf: ["sha256", "murmur128"]
        db: ["mongo7", "postgres15"]
        cache_db: ["redis7"]
        pump: ["tykio/tyk-pump-docker-pub:v1.8", "$ECR/tyk-pump:master"]
        sink: ["tykio/tyk-mdcb-docker:v2.4", "$ECR/tyk-sink:master"]
        exclude: 
          - pump: tykio/tyk-pump-docker-pub:v1.8
            sink: $ECR/tyk-sink:master
          - pump: $ECR/tyk-pump:master
            sink: tykio/tyk-mdcb-docker:v2.4
          - db: mongo7
            conf: murmur128
          - db: postgres15
            conf: sha256
        include:
          - db: postgres15
            markers: "and not sql"
            {{- template "auto-test" (dict "test" $test "repo" .Name "features" .Branchvals.Features) }}