package pkgs

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestRenderRetiredVersions(t *testing.T) {
	plans := []Plan{
		{Repo: "tyk-gateway", Track: "gateway", Cutoff: "v5.5", Product: "Tyk Gateway"},
		// no product: falls back to title-casing the repo name
		{Repo: "tyk-dashboard", Track: "gateway", Cutoff: "v5.5"},
		// not track-driven, must not appear
		{Repo: "tyk-pump", Cutoff: "v1.0.0"},
		{Repo: "tyk-identity-broker"},
	}
	want := `{/* This table is generated by gromit from the release tracks
    configuration. Do not edit it by hand: changes will be
    overwritten by the next sync. */}

| Product | Retained from | Retired below |
|---------|---------------|---------------|
| Tyk Dashboard | 5.5.x | 5.5.0 |
| Tyk Gateway | 5.5.x | 5.5.0 |
`
	assert.Equal(t, want, RenderRetiredVersions(plans))
}

func TestProductName(t *testing.T) {
	assert.Equal(t, "Tyk Gateway", ProductName("tyk-gateway"))
	assert.Equal(t, "Tyk Sync", ProductName("tyk-sync"))
}
