package pkgs

import (
	"fmt"
	"sort"
	"strings"

	"golang.org/x/mod/semver"
)

// ProductName title-cases a repo name, the fallback for plans that
// predate the product field
func ProductName(repo string) string {
	words := strings.Split(repo, "-")
	for i, w := range words {
		if w == "" {
			continue
		}
		words[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(words, " ")
}

// RenderRetiredVersions renders the tyk-docs retirement table from a
// plan. Only track-driven repos appear, so the published table cannot
// disagree with what pruning will do.
func RenderRetiredVersions(plans []Plan) string {
	var b strings.Builder
	b.WriteString(`{/* This table is generated by gromit from the release tracks
    configuration. Do not edit it by hand: changes will be
    overwritten by the next sync. */}

| Product | Retained from | Retired below |
|---------|---------------|---------------|
`)
	rows := make([]string, 0, len(plans))
	for _, p := range plans {
		if p.Track == "" || p.Cutoff == "" {
			continue
		}
		series := strings.TrimPrefix(semver.MajorMinor(p.Cutoff), "v")
		oldest := strings.TrimPrefix(semver.Canonical(p.Cutoff), "v")
		name := p.Product
		if name == "" {
			name = ProductName(p.Repo)
		}
		rows = append(rows, fmt.Sprintf("| %s | %s.x | %s |\n", name, series, oldest))
	}
	sort.Strings(rows)
	for _, r := range rows {
		b.WriteString(r)
	}
	return b.String()
}
