package policy

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)


func gitInTest(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(),
		"GIT_AUTHOR_NAME=test", "GIT_AUTHOR_EMAIL=test@test.co",
		"GIT_COMMITTER_NAME=test", "GIT_COMMITTER_EMAIL=test@test.co",
	)
	out, err := cmd.CombinedOutput()
	require.NoErrorf(t, err, "git %v: %s", args, out)
}


func TestNonTrivialDiff(t *testing.T) {
	dir := t.TempDir()
	gitInTest(t, dir, "init", "-q")

	relPath := filepath.Join(dir, "release.yml")
	const committed = "# Generated by: gromit policy\nname: Release\ntimeout: 30\n"
	require.NoError(t, os.WriteFile(relPath, []byte(committed), 0644))
	gitInTest(t, dir, "add", "-A")
	gitInTest(t, dir, "commit", "-qm", "init")

	t.Run("real content edit is flagged", func(t *testing.T) {
		require.NoError(t, os.WriteFile(relPath, []byte("# Generated by: gromit policy\nname: Release\ntimeout: 40\n"), 0644))
		defer gitInTest(t, dir, "checkout", "-q", "--", "release.yml")

		dfs, err := NonTrivialDiff(dir, false, false)
		require.NoError(t, err)
		assert.Equal(t, []string{"release.yml"}, dfs)
	})

	t.Run("marker-only change is ignored", func(t *testing.T) {
		require.NoError(t, os.WriteFile(relPath, []byte("# Generated by: gromit policy v2\nname: Release\ntimeout: 30\n"), 0644))
		defer gitInTest(t, dir, "checkout", "-q", "--", "release.yml")

		dfs, err := NonTrivialDiff(dir, false, false)
		require.NoError(t, err)
		assert.Empty(t, dfs)
	})
}
