#!/bin/sh

# Generated by: gromit policy

if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/portal.service ]; then
        cp /opt/portal/install/inits/systemd/system/portal.service /lib/systemd/system/portal.service
    fi
else
    if [ ! -f /etc/init.d/portal ]; then
        cp /opt/portal/install/inits/sysv/init.d/portal /etc/init.d/portal
    fi
fi
