tyk_release_branches = [
  { branch    = "master",
    reviewers = 2,
    convos    = false,
  required_tests = ["Go 1.16 Redis 5"] },
  { branch        = "release-4.3",
    reviewers     = 0,
    convos        = false,
    source_branch = "release-4",
  required_tests = ["Go 1.16 Redis 5"] },
  { branch        = "release-4.3.0",
    reviewers     = 0,
    convos        = false,
    source_branch = "release-4",
  required_tests = ["Go 1.16 Redis 5"] },
]  