#!/bin/sh

# Generated by: gromit policy

if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/midsommar.service ]; then
        cp /opt/midsommar/install/inits/systemd/system/midsommar.service /lib/systemd/system/midsommar.service
    fi
else
    if [ ! -f /etc/init.d/midsommar ]; then
        cp /opt/midsommar/install/inits/sysv/init.d/midsommar /etc/init.d/midsommar
    fi
fi
