name: API Regresion Tests
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - 'tests/api/**'
  push:
    branches:
      - master
      - release-*
    paths:
      - 'tests/api/**'
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      tags: {{`${{ steps.metadata.outputs.tags }}`}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install flake for linting
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        working-directory: tests/api
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::754489498669:role/ecr_rw_tyk
          role-session-name: cipush
          aws-region: eu-central-1
      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr
        with:
          mask-password: 'true'
          mask-aws-account-id: 'true'
          
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: {{`${{ steps.ecr.outputs.registry }}`}}/tyk-automated-tests
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=sha,format=long,prefix=
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: tests/api
          file: tests/api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: {{`${{ steps.metadata.outputs.tags }}`}}
          labels: {{`${{ steps.metadata.outputs.labels }}`}}
          cache-from: type=gha
          cache-to: type=gha,mode=max  
  {{ $Tests := list "api-gate"  }}
  {{ $Branchvals := dict "Features" .Branchvals.Features "Tests" $Tests  }}
  {{- template "auto-test" (dict "Name" .Name "Branchvals" $Branchvals) }}