#!/bin/sh

# Generated by: gromit policy

if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/tyk-sink.service ]; then
        cp /opt/tyk-sink/install/inits/systemd/system/tyk-sink.service /lib/systemd/system/tyk-sink.service
    fi
else
    if [ ! -f /etc/init.d/tyk-sink ]; then
        cp /opt/tyk-sink/install/inits/sysv/init.d/tyk-sink /etc/init.d/tyk-sink
    fi
fi
