
# Generated by: gromit policy
# Generated on: {{ .Timestamp }}

{{ $tf_env := "prod" }}

data "terraform_remote_state" "integration" {
  backend = "remote"

  config = {
    organization = "Tyk"
    workspaces = {
      name = "base-{{ $tf_env }}"
    }
  }
}

output "{{ .Name }}" {
  value = data.terraform_remote_state.integration.outputs.{{ .Name }}
  description = "ECR creds for {{ .Name }} repo"
}

output "region" {
  value = data.terraform_remote_state.integration.outputs.region
  description = "Region in which the env is running"
}
