name: Api Tests

on:
  workflow_call:

jobs:
{{ $test := "ui" }}
  test-controller-{{ $test }}:
{{ template "test-controller" (dict "test" $test) }}
  api-tests:   
    {{ template "tests" (dict "test" $test "repo" .Name) }}