name: Api Tests

on:
  workflow_call:

jobs:
{{ $test := "ui" }}
  test-controller-{{ $test }}:
    runs-on: ubuntu-latest
{{ template "test-controller" (dict "test" $test "repo" .Name) }}
  {{ $test }}-tests: 
    runs-on: ubuntu-latest
    needs: test-controller-{{ $test }} 
    {{ template "tests" (dict "test" $test "repo" .Name) }}