# This file contains github policy that is used to generate all the releng
# automation, and any other automation including automated PR generation
# from gromit.

git:
  # `prefix` is used to derive the fully qualified github URL for the repos
  prefix: https://github.com/TykTechnologies

# `policy` is the root object for the policy and bundle commands. Any
# parent policy options provided here can be overridden by repo
# specific/ branch specific options.
policy:
  # Repo specific policies start here->
  repos:
    # Repo specific policy for `tyk` starts here->
    tyk:
      # Description for the repo - this will be used as description for
      # deb/rpm packages, docker images etc.
      description: >-
        Tyk Open Source API Gateway written in Go, supporting REST, GraphQL, TCP and gRPC protocols
      # The packagecloud repo name for this git repo.
      pcrepo: tyk-gateway
      # The dockerhub image name for this repo. in the form of repo/image
      dhrepo: tykio/tyk-gateway
      # Cloudsmith image name for this repo.
      csrepo: docker.tyk.io/tyk-gateway/tyk-gateway
      # `reviewers` take a list of github users/teams
      # (eg: TykTechnologies/devops) that will be automatically set as
      # reviewers for any automated PRs generated for this repo.
      # It also is used while generating dependabot templates to set
      # reviewers for PRs opened by dependabot.
      reviewers: []
      # The name for the deb/rpm packages generated by release workflow.
      packagename: tyk-gateway
      # The name of the binary generated after the build.
      binary: tyk
      # `protected` specifies repo specific protected branches - this gets
      # appended to the common protected branches if any.
      # Ports exposed by the docker images built for this repo/
      exposeports: "8080"
      # Specifies whether this repo had to be built with cgo
      # enabled. This will also generate separate packages for
      # older glibc versions (el7 and non-el7 release workflows)
      cgo: true
      # The version that's used for upgrade tests. This version
      # will be installed first and will then be upgraded with the
      # recently generated packages. Make sure that this is a version
      # that has candidate packages for all our supported OSes and archs.
      upgradefromver: 3.0.8
      # This signifies whether the packagecloud repo for this git repo
      # is private or not.
      pcprivate: false
      # The default config file used by the application.
      configfile: tyk.conf
      # The go package which contains the `VERSION` string for this REPO.
      versionpackage: github.com/TykTechnologies/tyk/gateway
      # Min number of reviews needed for a PR
      reviewcount: 0
      # Should conversations be resolved before merging
      convos: false
      # features act as flags whose presence/absence can be used to
      # render a common set of features across branch(es)
      # For eg: there are some branches that support el/7, and some that doesn't - to
      # render el/7 support on these branches, add  `el7` as a feature of these
      # branches and write the template conditions accordingly to render the templates
      # with el7 support based on the presence of this flag
      features:
        - releng
      # Different branches could have different policy as older branches
      # could be on a different releaese workflow. To override any branch
      # policy for a specific branch, they could be specified here, under
      # the respective branches.
      # Branch specific policy for different branches starts here.->
      branches:
        master:
          # The build environment used for this repo. Right now, this value
          # is used for selecting the appropriate golang-cross image
          # used for building the binary, packages and docker images.
          buildenv: 1.19-bullseye
          reviewcount: 1
          # Workflows that need to pass to merge PRs
          tests:
            - "Go 1.19.x Redis 5"
            - "1.19-bullseye"
          features:
            - go1.19
        release-5.1:
          buildenv: 1.19-bullseye
        release-5.1.1:
          buildenv: 1.19-bullseye
        release-4-lts:
          tests:
            - "Go 1.15 Redis 6"
          features:
            - el7
            - plugin-compiler-fix-vendor
          buildenv: 1.15
        release-5.0.4:
          sourcebranch: release-5-lts
          tests: ["Go 1.16 Redis 5","1.16","1.16-el7"]
          buildenv: 1.16
          features:
            - el7
            - plugin-compiler-fix-vendor
          release-5.0.5:
            sourcebranch: release-5-lts
            tests: ["Go 1.16 Redis 5","1.16","1.16-el7"]
            buildenv: 1.16
            features:
              - el7
              - plugin-compiler-fix-vendor
          release-5.1.12:
            sourcebranch: release-5.1
            tests: ["Go 1.16 Redis 5","1.16","1.16-el7"]
            buildenv: 1.16
            features:
              - el7
              - plugin-compiler-fix-vendor
          release-5-lts:
            buildenv: 1.16
            tests: ["Go 1.16 Redis 5","1.16-bullseye","1.16-el7"]
            features:
              - el7
              - plugin-compiler-fix-vendor
          release-4.0.14:
            sourcebranch: release-4-lts
            buildenv: 1.15
            tests:
              - "Go 1.15 Redis 6"
            features:
              - plugin-compiler-fix-vendor
              - el7

    tyk-analytics:
      description: >-
        Dashboard for the Tyk API Gateway
      pcrepo: tyk-dashboard
      dhrepo: tykio/tyk-dashboard
      csrepo: docker.tyk.io/tyk-dashboard/tyk-dashboard
      exposeports: "3000 5000"
      binary: tyk-analytics
      reviewers: []
      packagename: tyk-dashboard
      cgo: true
      upgradefromver: 3.0.9
      pcprivate: false
      configfile: tyk_analytics.conf
      versionpackage: github.com/TykTechnologies/tyk-analytics/dashboard
      convos: false
      sourcebranch: master          
      buildenv: 1.16
      reviewcount: 0
      tests: ["1.19-bullseye","test (1.19.x, ubuntu-latest, amd64, 15.x)","postgres","sqlite","mongo-mgo","mongo-official"]
      branches:
        master:
          reviewcount: 1
          buildenv: 1.19-bullseye
          features:
            - go1.19
        release-5.1:
          reviewcount: 0
          buildenv: 1.19-bullseye
          features:
            - go1.19
        release-5.1.1:
          reviewcount: 0
          buildenv: 1.19-bullseye
          features:
            - go1.19
        release-5.0.4:
          sourcebranch: release-5-lts
          tests: ["1.16","1.16-el7","test (1.16.x, ubuntu-latest, amd64, 15.x)","sqlite","mongo-mgo","mongo-official"]
          features:
            - el7
        release-5-lts:
          tests: ["1.16","1.16-el7","test (1.16.x, ubuntu-latest, amd64, 15.x)","sqlite","mongo-mgo","mongo-official"]
          features:
            - el7
        release-4-lts:
          tests: ["1.16","1.16-el7","test (1.16.x, ubuntu-latest, amd64, 15.x)","sqlite","mongo"]
          features:
            - el7
        release-4.0.14:
          tests: ["1.16","1.16-el7","test (1.16.x, ubuntu-latest, amd64, 15.x)","sqlite","mongo"]
          features:
            - el7

    tyk-identity-broker:
      description: >-
        Tyk Authentication Proxy for third-party login
      pcrepo: tyk-identity-broker
      dhrepo: tykio/tyk-identity-broker
      csrepo: docker.tyk.io/tyk-identity-broker/tyk-identity-broker
      exposeports: 80
      binary: tyk-identity-broker
      reviewers: [ TykTechnologies/platform-squad ]
      packagename: tyk-identity-broker
      cgo: false
      upgradefromver: 1.1.0
      pcprivate: false
      configfile: tib.conf
      versionpackage: github.com/TykTechnologies/tyk-identity-broker/main
      buildenv: 1.19-bullseye
      tests: ["1.19-bullseye"]
      branches:
        master:
          reviewcount: 1
          buildenv: 1.19-bullseye

    tyk-sink:
      description: >-
       Tyk RPC server backend (bridge)
      pcrepo: tyk-mdcb
      dhrepo: tykio/tyk-mdcb-docker
      csrepo: docker.tyk.io/tyk-sink/tyk-sink
      exposeports: 80
      binary: tyk-sink
      reviewers: [ TykTechnologies/platform-squad ]
      packagename: tyk-sink
      cgo: false
      upgradefromver: 1.8.2
      pcprivate: true
      configfile: tyk_sink.conf
      versionpackage: github.com/TykTechnologies/tyk-sink/main
      sourcebranch: master        
      buildenv: 1.19-bullseye
      tests: ["1.19-bullseye", "postgres", "mongo-official", "mongo-mgo"]
      branches:
        master:
          reviewcount: 1
          buildenv: 1.19-bullseye
            
    portal:
      description: >-
        Developer portal for the Tyk API Gateway
      pcrepo: portal
      dhrepo: tykio/portal
      exposeports: 80
      reviewers: []
      binary: dev-portal
      packagename: portal
      cgo: true
      upgradefromver: 1.0.0
      pcprivate: false
      configfile: portal.conf
      versionpackage: github.com/TykTechnologies/portal/core
      convos: false
      tests:
        - "test (1.19.x, ubuntu-latest, amd64, 15.x)"
        - "1.19-bullseye"
      buildenv: 1.19-bullseye
      branches:
        master:
          reviewcount: 1
          buildenv: 1.19-bullseye
          tests:
            - "test (1.19.x, ubuntu-latest, amd64, 15.x)"
            - "1.19-bullseye"
          features:
            - "go1.19"
        release-1.0:
          buildenv: 1.15
          tests:
            - "test (1.16.x, ubuntu-latest, amd64, 15.x)"
            - "1.15"
            - "1.15-el7"

    tyk-pump:
      description: >-
        Tyk Analytics Pump to move analytics data from Redis to any supported back end (multiple back ends can be written to at once).
      pcrepo: tyk-pump
      dhrepo: tykio/tyk-pump-docker-pub
      csrepo: docker.tyk.io/tyk-pump/tyk-pump
      reviewers: [ TykTechnologies/platform-squad ]
      exposeports: "80"
      binary: tyk-pump
      packagename: tyk-pump
      cgo: false
      upgradefromver: 1.6.0
      pcprivate: false
      configfile: pump.conf
      versionpackage: github.com/TykTechnologies/tyk-pump/pumps
      convos: false
      sourcebranch: master
      buildenv: 1.19-bullseye
      tests: ["1.19-bullseye","Go 1.19 tests"]
      features:
        - go1.19
      branches:
        master:
          reviewcount: 1
          buildenv: 1.19-bullseye

    tyk-analytics-ui:
      description: >-
        User interface for our dashboard. Backend: https://github.com/TykTechnologies/tyk-analytics
      pcrepo: tyk-analytics-ui
      dhrepo: tykio/tyk-analytics-ui
      csrepo: docker.tyk.io/tyk-analytics-ui/tyk-analytics-ui
      exposeports: 80
      reviewers: []
      binary: tyk-analytics-ui
      packagename: tyk-analytics-ui
      sourcebranch: master
      branches:
        master:
          reviewcount: 1
          tests: ["test (1.16.x, ubuntu-latest, amd64, 15.x)","test"]
        release-5.1:
          reviewcount: 0
          tests: [ "test (1.19.x, 1.16.x, ubuntu-latest, amd64, 15.x)", "test" ]
        release-5.1.1:
          sourcebranch: release-5.1
          reviewcount: 0
          tests: [ "test (1.19.x, 1.16.x, ubuntu-latest, amd64, 15.x)", "test" ]            
        release-5.0.4:
          sourcebranch: release-5-lts
          tests: ["test (1.16.x, ubuntu-latest, amd64, 15.x)", "test"]
        release-5-lts:
          tests: ["test (1.16.x, ubuntu-latest, amd64, 16)", "test"]
        release-4-lts:
          tests: []
        release-4.0.14:
          tests: []
