# This file contains github policy that is used to generate all the releng
# automation, and any other automation including automated PR generation
# from gromit.

git:
  # `prefix` is used to derive the fully qualified github URL for the repos
  prefix: https://github.com/TykTechnologies

# `policy` is the root object for the policy and bundle commands. Any
# parent policy options provided here can be overridden by repo
# specific/ branch specific options.
policy:
  # `protected` takes a list of branches which are deemed to be protected.
  # Gromit wil never directly make any changes on these branches, and will
  # work only with PRs.
  protected: [ master ]
  # `default` takes a single branch name which is the default branch for all
  # the repos. If a repo has a different default branch, say `main`  - this
  # common policy option can be overridden at the branch policy level.
  default: master
  # Public or private
  visibility: "private"
  # Enables wiki feature for the given repo
  wiki: false
  # Enables alerts over vulnerability scans for dependabot and others
  vulnerabilityalerts: false
  # Squash merge commit body
  squashmsg: PR_BODY
  # Squash merge commit title
  squashtitle: PR_TITLE
  # Repo specific policies start here->
  repos:
    # Repo specific policy for `tyk` starts here->
    tyk:
      # Description for the repo - this will be used as description for
      # deb/rpm packages, docker images etc.
      description: >-
        Tyk Open Source API Gateway written in Go, supporting REST, GraphQL, TCP and gRPC protocols
      # The packagecloud repo name for this git repo.
      pcrepo: tyk-gateway
      # The dockerhub image name for this repo. in the form of repo/image
      dhrepo: tykio/tyk-gateway
      # Cloudsmith image name for this repo.
      csrepo: docker.tyk.io/tyk-gateway/tyk-gateway
      # `reviewers` take a list of github users/teams
      # (eg: TykTechnologies/devops) that will be automatically set as
      # reviewers for any automated PRs generated for this repo.
      # It also is used while generating dependabot templates to set
      # reviewers for PRs opened by dependabot.
      reviewers: []
      # The name for the deb/rpm packages generated by release workflow.
      packagename: tyk-gateway
      # The name of the binary generated after the build.
      binary: tyk
      # `protected` specifies repo specific protected branches - this gets
      # appended to the common protected branches if any.
      protected: [ release-3-lts, release-4 ]
      # Ports exposed by the docker images built for this repo/
      exposeports: "8080"
      # Repository topics
      topics: ["api", "api-gateway", "api-management", "cloudnative", "go", "graphql", "grpc", "k8s", "kubernetes", "microservices", "reverse-proxy", "tyk"]
      visibility: "public"
      vulnerabilityalerts: true
      # Common branch policy for all branches for this
      # repo starts here->
      branches:
          # Specifies whether this repo had to be built with cgo
          # enabled. This will also generate separate packages for
          # older glibc versions (el7 and non-el7 release workflows)
          cgo: true
          # The go version used for this repo. Right now, this value
          # is used for selecting the appropriate golang-cross image
          # used for building the binary, packages and docker images.
          goversion: 1.16
          # The version that's used for upgrade tests. This version
          # will be installed first and will then be upgraded with the
          # recently generated packages. Make sure that this is a version
          # that has candidate packages for all our supported OSes and archs.
          upgradefromver: 3.0.8
          # This signifies whether the packagecloud repo for this git repo
          # is private or not.
          pcprivate: false
          # The default config file used by the application.
          configfile: tyk.conf
          # The go package which contains the `VERSION` string for this REPO.
          versionpackage: github.com/TykTechnologies/tyk/gateway
          # Min number of reviews needed for a PR
          reviewcount: 0
          # Should conversations be resolved before merging
          convos: false
          # Workflows that need to pass before merging
          tests: ["Go 1.16 Redis 5","1.16","1.16-el7"]
          # Specifies which version of releng templates to use - this can be
          # overridden by branch specific policy in the branch section.
          # Branches automatically inherit the version of the source branch unless
          # overridden explicitly.
          # Any branch that doesn't have a source branch and explicit relengversion
          # will use the version set here.
          relengversion: release-5.x
          # Branch specific policy for different branches starts here.->
          # Different branches could have different policy as older branches
          # could be on a different releaese workflow. To override any branch
          # policy for a specific branch, they could be specified here, under
          # the respective branches.
          branch:
            master:
              # For any branch other than master, setting active to true also implies
              # that it is a sync automation target.
              # any changes that land in master will be picked and made in to PRs
              # against all the branches that has active set to `true`.
              # Please note that the automation picks only ci specific commits. (Selected
              # workflows form .github/workflows/*, the ci/ directory and some other files.
              # For up to date info on this, please refer to the latest sync automation
              # templates.
              active: true
              reviewcount: 1
            release-3-lts:
              active: false
              goversion: 1.12
              upgradefromver: 3.0.4
              relengversion: release-3.x
            release-4:
              active: false
              relengversion: release-4.x
            release-4.3:
              active: true
              sourcebranch: release-4
            release-4.3.0:
              active: false
              sourcebranch: release-4
            release-4.3.1:
              active: false
              sourcebranch: release-4.3
            release-4.3.2:
              active: false
              sourcebranch: release-4.3
            release-4.3.3:
              active: false
              sourcebranch: release-4.3
            release-4.0.10:
              active: false
              sourcebranch: release-4-lts
              tests: [ "Go 1.15 Redis 5","1.15","1.15-el7"]
            release-4.0.11:
              active: false
              sourcebranch: release-4-lts
              tests: [ "Go 1.15 Redis 5","1.15","1.15-el7"]
            release-4.0.12:
              active: false
              sourcebranch: release-4-lts
              tests: [ "Go 1.15 Redis 5","1.15","1.15-el7"]
            release-4-lts:
              active: true
              tests: [ "Go 1.15 Redis 5","1.15","1.15-el7"]
              relengversion: release-4.x
            release-4.0.13:
              active: false
              sourcebranch: release-4-lts
              tests: [ "Go 1.15 Redis 5","1.15","1.15-el7"]
            release-5.0:
              active: true
              sourcebranch: master
              tests: ["Go 1.16 Redis 5","1.16","1.16-el7"]
            release-5.0.1:
              active: false
              sourcebranch: release-5-lts
              tests: ["Go 1.16 Redis 5","1.16","1.16-el7"]
            release-5-lts:
              active: true
              sourcebranch: master
              tests: ["Go 1.16 Redis 5","1.16","1.16-el7"]
    tyk-analytics:
      description: >-
        Tyk Dashboard New Repository
      pcrepo: tyk-dashboard
      dhrepo: tykio/tyk-dashboard
      csrepo: docker.tyk.io/tyk-dashboard/tyk-dashboard
      exposeports: "3000 5000"
      binary: tyk-analytics
      reviewers: []
      packagename: tyk-dashboard
      protected: [ release-3-lts, release-4, release-4-lts ]
      wiki: true
      vulnerabilityalerts: true
      branches:
          cgo: true
          goversion: 1.16
          upgradefromver: 3.0.9
          pcprivate: false
          configfile: tyk_analytics.conf
          versionpackage: github.com/TykTechnologies/tyk-analytics/dashboard
          convos: false
          tests: ["1.16","1.16-el7","test (1.16.x, ubuntu-latest, amd64, 15.x)","sqlite","mongo"]
          reviewcount: 0
          branch:
            release-3-lts:
              active: false
              goversion: 1.12
              upgradefromver: 3.0.4
            master:
              active: true
              reviewcount: 1
            release-4:
              active: false
            release-4.3:
              active: true
              sourcebranch: release-4
            release-4.3.0:
              active: false
              sourcebranch: release-4
            release-4.3.1:
              active: false
              sourcebranch: release-4.3
            release-4.3.2:
              active: false
              sourcebranch: release-4.3
            release-4.3.3:
              active: false
              sourcebranch: release-4.3
            release-4.0.10:
              active: false
              sourcebranch: release-4-lts
            release-4.0.11:
              active: false
              sourcebranch: release-4-lts
            release-4.0.12:
              active: false
              sourcebranch: release-4-lts
            release-4-lts:
              active: true
            release-4.0.13:
              active: false
              sourcebranch: release-4-lts
            release-5.0:
              active: true
              sourcebranch: master
            release-5-lts:
              active: true
              sourcebranch: master
            release-5.0.1:
              active: false
              sourcebranch: release-5-lts
    tyk-pump:
      description: >-
        Tyk Analytics Pump to move analytics data from Redis to any supported back end (multiple back ends can be written to at once).
      pcrepo: tyk-pump
      dhrepo: tykio/tyk-pump-docker-pub
      csrepo: docker.tyk.io/tyk-pump/tyk-pump
      reviewers: [ TykTechnologies/platform-squad ]
      exposeports: "80"
      binary: tyk-pump
      packagename: tyk-pump
      protected: [ release-1.6, release-1.5 ]
      squashmsg: COMMIT_MESSAGES
      squashtitle: COMMIT_OR_PR_TITLE
      visibility: "public"
      vulnerabilityalerts: true
      branches:
          cgo: false
          goversion: 1.15
          upgradefromver: 1.6.0
          pcprivate: false
          configfile: pump.conf
          versionpackage: github.com/TykTechnologies/tyk-pump/pumps
          convos: false
          tests: ["1.15","Go 1.16 tests"]
          reviewcount: 0
          branch:
            master:
              active: true
              reviewcount: 2
            release-1.7:
              active: true
    tyk-identity-broker:
      description: >-
        Tyk Authentication Proxy for third-party login
      pcrepo: tyk-identity-broker
      dhrepo: tykio/tyk-identity-broker
      csrepo: docker.tyk.io/tyk-identity-broker/tyk-identity-broker
      exposeports: 80
      binary: tyk-identity-broker
      reviewers: [ TykTechnologies/platform-squad ]
      packagename: tyk-identity-broker
      protected: [ master, release-1.3, release-1.2 ]
      wiki: true
      squashmsg: COMMIT_MESSAGES
      squashtitle: COMMIT_OR_PR_TITLE
      visibility: "public"
      vulnerabilityalerts: true
      branches:
        cgo: false
        goversion: 1.15
        upgradefromver: 1.1.0
        pcprivate: false
        configfile: tib.conf
        versionpackage: github.com/TykTechnologies/tyk-identity-broker/main
        convos: false
        tests: ["1.16"]
        reviewcount: 0
        branch:
          master:
            active: true
            reviewcount: 1
          release-1.4:
            active: true
          release-1.3:
            active: true
          release-1.2:
            active: true
            tests: ["1.15"]
    tyk-sink:
      description: >-
       Tyk RPC server backend (bridge)
      pcrepo: tyk-mdcb
      dhrepo: tykio/tyk-mdcb-docker
      csrepo: docker.tyk.io/tyk-sink/tyk-sink
      exposeports: 80
      binary: tyk-sink
      reviewers: [ TykTechnologies/platform-squad ]
      packagename: tyk-sink
      protected: [ master, release-2, release-1.8 ]
      wiki: true
      squashmsg: COMMIT_MESSAGES
      squashtitle: COMMIT_OR_PR_TITLE
      branches:
        cgo: false
        goversion: 1.16
        upgradefromver: 1.8.2
        pcprivate: true
        configfile: tyk_sink.conf
        versionpackage: github.com/TykTechnologies/tyk-sink/main
        convos: false
        tests: ["1.16"]
        reviewcount: 0
        branch:
          master:
            active: true
            reviewcount: 1
          release-2:
            active: false
          release-2.1:
            active: true
    portal:
      description: >-
        Portal is a full-featured developer portal, blog and CMS
      pcrepo: portal
      dhrepo: tykio/portal
      csrepo: docker.tyk.io/portal/portal
      exposeports: 80
      reviewers: []
      binary: dev-portal
      packagename: portal
      protected: [ master, release-1.0 ]
      topics: [ api-gateway, portal ]
      wiki: true
      squashmsg: COMMIT_MESSAGES
      squashtitle: COMMIT_OR_PR_TITLE
      branches:
        cgo: true
        goversion: 1.15
        upgradefromver: 1.0.0
        pcprivate: false
        configfile: portal.conf
        versionpackage: github.com/TykTechnologies/portal/core
        convos: false
        tests: ["test (1.19.x, ubuntu-latest, amd64, 15.x)","Go 1.19 (bullseye)"]
        reviewcount: 0
        branch:
          master:
            active: true
            reviewcount: 1
          release-1.0:
            active: true
            tests: ["test (1.16.x, ubuntu-latest, amd64, 15.x)","1.15","1.15-el7"]
    tyk-analytics-ui:
      description: >-
        User interface for our dashboard. Backend: https://github.com/TykTechnologies/tyk-analytics
      pcrepo: tyk-analytics-ui
      dhrepo: tykio/tyk-analytics-ui
      csrepo: docker.tyk.io/tyk-analytics-ui/tyk-analytics-ui
      exposeports: 80
      reviewers: []
      binary: tyk-analytics-ui
      packagename: tyk-analytics-ui
      protected: [ master ]
      wiki: true
      vulnerabilityalerts: true
      branches:
        convos: false
        tests: ["test (1.16.x, ubuntu-latest, amd64, 15.x)", "test"]
        reviewcount: 0
        branch:
          master:
            active: true
            reviewcount: 2
          release-4.3:
            active: true
            sourcebranch: release-4
          release-4.3.0:
            active: false
            sourcebranch: release-4
          release-4.3.1:
            active: false
            sourcebranch: release-4.3
          release-4.3.2:
            active: false
            sourcebranch: release-4.3
          release-4.3.3:
            active: false
            sourcebranch: release-4.3
          release-4.0.10:
            active: false
            sourcebranch: release-4-lts
            tests: []
          release-4.0.11:
            active: false
            sourcebranch: release-4-lts
            tests: []
          release-4.0.12:
            active: false
            sourcebranch: release-4-lts
            tests: []
          release-4-lts:
            active: true
          release-4.0.13:
            active: false
            sourcebranch: release-4-lts
            tests: []
          release-5.0:
            active: true
            sourcebranch: master
          release-5.0.1:
            active: false
            sourcebranch: release-5-lts
          release-5-lts:
            active: true
            sourcebranch: master
            tests: ["test (1.16.x, ubuntu-latest, amd64, 16)", "test"]
