name: Release

on:
  pull_request:
    paths:
      - 'auto/**'   
  push:
    paths:
      - 'auto/**'    
    tags:
      - 'v*'
    
jobs:
{{- template "auto-test" . }}
  release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [api-tests,ui-tests]
    permissions:
      contents: write  
    steps:
      - uses: actions/checkout@v3
          
      - name: CI env
        run:
          tar czf ci-env.tgz auto/

      - uses: softprops/action-gh-release@v1
        with:
          token: {{`${{ secrets.ORG_GH_TOKEN }}`}}
          name: {{`${{ github.ref_name }}`}}
          tag_name: {{`${{ github.ref_name }}`}}
          body_path: auto/release.md
          files: ci-env.tgz