name: Test²
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
{{- if eq .Name "tyk-analytics" }}
      - 'tests/ui/**'
      - 'tests/api/**'
{{- else if eq .Name "tyk-ci" }}
      - 'auto/**'   
{{- end }}
  push:
    branches:
      - master
      - release-*
    paths:
{{- if eq .Name "tyk-analytics" }}
      - 'tests/ui/**'
      - 'tests/api/**'
{{- else if eq .Name "tyk-ci" }}
      - 'auto/**'   
{{- end }}

jobs:
{{- $DOT := . }}
{{- range $test := .Branchvals.Tests }}
{{- template "auto-test" (dict "dot" $DOT "test" $test) }}
{{- end }}

{{ if eq .Name "tyk-ci" }}
  release:
    if: {{`${{ startsWith(github.ref, 'refs/tags') }}`}}
    runs-on: ubuntu-latest
    needs:
    {{- range $test := .Branchvals.Tests }}
      - {{ $test }}
    {{- end }}
    permissions:
      contents: write  
    steps:
      - uses: actions/checkout@v3
          
      - name: CI env
        run:
          tar czf ci-env.tgz auto/

      - uses: softprops/action-gh-release@v1
        with:
          token: {{`${{ secrets.ORG_GH_TOKEN }}`}}
          name: {{`${{ github.ref_name }}`}}
          tag_name: {{`${{ github.ref_name }}`}}
          body_path: auto/release.md
          files: ci-env.tgz
{{- end }} {{/* tyk-ci */}}
