name: Test²
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
{{- if eq .Name "tyk-analytics" }}
    paths:
      - 'tests/ui/**'
      - 'tests/api/**'
{{- end }}
  push:
{{- if eq .Name "tyk-pro" }}
    tags:
      - 'v*'
{{- end }}
    branches:
      - master
      - release-*
{{- if eq .Name "tyk-analytics" }}
    paths:
      - 'tests/ui/**'
      - 'tests/api/**'
{{- end }}

jobs:
{{- $DOT := . }}
{{- range $test := .Branchvals.Tests }}
  {{- template "auto-test" (dict "dot" $DOT "test" $test) }}
{{- end }}

{{ if eq .Name "tyk-pro" }}
  release:
    if: {{`${{ startsWith(github.ref, 'refs/tags') }}`}}
    runs-on: ubuntu-latest
    needs:
    {{- range $test := .Branchvals.Tests }}
      - {{ $test }}-tests
    {{- end }}
    permissions:
      contents: write  
    steps:
      - uses: actions/checkout@v3

      - uses: softprops/action-gh-release@v1
        with:
          token: {{`${{ secrets.ORG_GH_TOKEN }}`}}
          name: {{`${{ github.ref_name }}`}}
          tag_name: {{`${{ github.ref_name }}`}}
          body_path: release.md
{{- end }} {{/* tyk-pro */}}
