name: Test²
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
{{- if eq .Name "tyk-analytics" }}
    paths:
      - 'tests/ui/**'
      - 'tests/api/**'
{{- end }}
  push:
{{- if eq .Name "tyk-pro" }}
    tags:
      - 'v*'
{{- end }}
    branches:
      - master
      - release-*
{{- if eq .Name "tyk-analytics" }}
    paths:
      - 'tests/ui/**'
      - 'tests/api/**'
{{- end }}

env:
  VARIATION: prod-variation
  BASE_REF: {{`${{startsWith(github.event_name, 'pull_request') && github.base_ref || github.ref_name}}`}}

jobs:
{{- $DOT := . }}
{{- range $test := .Branchvals.Tests }}
  {{- template "auto-test" (dict "dot" $DOT "test" $test "flow" "test-square") }}
{{- end }}

{{ if eq .Name "tyk-pro" }}
  release:
    if: {{`${{ startsWith(github.ref, 'refs/tags') }}`}}
    # Backticks escape GitHub Actions syntax from Go template parsing
    runs-on: {{`${{ vars.DEFAULT_RUNNER }}`}}
    needs:
    {{- range $test := .Branchvals.Tests }}
      - {{ $test }}-tests
    {{- end }}
    permissions:
      contents: write  
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547  # v1
        with:
          app-id: {{`${{ secrets.PROBE_APP_ID }}`}}
          private-key: {{`${{ secrets.PROBE_APP_PRIVATE_KEY }}`}}
          owner: TykTechnologies

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - uses: softprops/action-gh-release@26994186c0ac3ef5cae75ac16aa32e8153525f77  # v1
        with:
          token: {{`${{ steps.app-token.outputs.token }}`}}
          name: {{`${{ github.ref_name }}`}}
          tag_name: {{`${{ github.ref_name }}`}}
          body_path: release.md
{{- end }} {{/* tyk-pro */}}
