name: UI Regresion Tests
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - 'tests/ui/**'
  push:
    branches:
      - master
      - release-*
    paths:
      - 'tests/ui/**'
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  {{ $Tests := list "ui-gate"  }}
  {{ $Branchvals := dict "Features" .Branchvals.Features "Tests" $Tests  }}
  {{- template "auto-test" (dict "Name" .Name "Branchvals" $Branchvals) }}