#!/bin/sh

# Generated by: gromit policy

if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/tyk-ai-studio.service ]; then
        cp /opt/tyk-ai-studio/install/inits/systemd/system/tyk-ai-studio.service /lib/systemd/system/tyk-ai-studio.service
    fi
else
    if [ ! -f /etc/init.d/tyk-ai-studio ]; then
        cp /opt/tyk-ai-studio/install/inits/sysv/init.d/tyk-ai-studio /etc/init.d/tyk-ai-studio
    fi
fi
