#!/bin/sh

# Generated by: gromit policy

if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/tyk-dashboard.service ]; then
        cp /opt/tyk-dashboard/install/inits/systemd/system/tyk-dashboard.service /lib/systemd/system/tyk-dashboard.service
    fi
else
    if [ ! -f /etc/init.d/tyk-dashboard ]; then
        cp /opt/tyk-dashboard/install/inits/sysv/init.d/tyk-dashboard /etc/init.d/tyk-dashboard
    fi
fi
