#!/bin/sh

# Generated by: gromit policy
# Generated on: {{ .Timestamp }}

if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/{{ .PackageName }}.service ]; then
        cp /opt/{{ .PackageName }}/install/inits/systemd/system/{{ .PackageName }}.service /lib/systemd/system/{{ .PackageName }}.service
    fi
else
    if [ ! -f /etc/init.d/{{ .PackageName }} ]; then
        cp /opt/{{ .PackageName }}/install/inits/sysv/init.d/{{ .PackageName }} /etc/init.d/{{ .PackageName }}
    fi
fi
