name: Dr. Releng

on:
  pull_request:
    # paths:
    #   - policy/templates/**

jobs:
  doctor:
    runs-on: ubuntu-latest
    container: tykio/gromit:v1.4.6-rc2
    strategy:
      fail-fast: false
      matrix:
        repo: [tyk]
        # repo: [tyk, tyk-analytics, tyk-pump, tyk-identity-broker, tyk-sink, portal]
        branch: [master]
        bundle: [releng]
        # bundle: [releng, sync]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: TykTechnologies/${{ matrix.repo }}
          token: ${{ secrets.ORG_GH_TOKEN }}
          path: ${{ matrix.repo }}

      - name: Generate
        run: gromit bundle --bundle ${{ matrix.bundle }} --repo ${{ matrix.repo }} gen ${{ matrix.repo }}

      - name: Check for zero diffs
        id: diff
        run: |
          gromit git diff ${{ matrix.repo }} || true
          echo "OUTPUT=This is an error" >> $GITHUB_ENV
          echo "::error file=${{ matrix.repo }}::${OUTPUT}"
