name: Policy as Code

on:
  pull_request:
    paths:
      - policy/terraform/**

env:
  TERRAFORM_DIR: "./policy/terraform"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::046805072452:role/gromit-test
          role-session-name: gromitci
          aws-region: eu-central-1

      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        working-directory: ${{ env.TERRAFORM_DIR }}
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_DIR }}
        id: init
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ${{ env.TERRAFORM_DIR }}
        id: init
        run: terraform plan
