# goreleaser knows not to publish when the trigger is _not_ a tag

name: Release

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  dep-guard:
    if: github.event_name == 'pull_request'
    uses: TykTechnologies/github-actions/.github/workflows/dependency-guard.yml@f867e501af8d103dd4b2a43a53f15c72d7de180f  # main

  goreleaser:
    needs: [dep-guard]
    if: always() && (needs.dep-guard.result == 'success' || needs.dep-guard.result == 'skipped')
    runs-on: ${{ vars.DEFAULT_RUNNER }}
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff  # v5
        with:
          go-version: "1.22"

      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f  # v3

      - run: make test

      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9  # v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a  # v6
        with:
          version: "~> v2"
          args: release --clean ${{ !startsWith(github.ref, 'refs/tags/') && '--snapshot' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GH_TOKEN }}

      - name: find amd64 linux binary
        id: binary
        run: |
          path=$(jq -rc '.[] | select((.type=="Binary") and (.goos=="linux") and .goarch=="amd64") | .path' dist/artifacts.json)
          echo "path=${path}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
        with:
          name: binary-amd64
          path: ${{ steps.binary.outputs.path }}
          retention-days: 1

  doctor:
    needs: goreleaser
    runs-on: ${{ vars.DEFAULT_RUNNER }}
    strategy:
      fail-fast: false
      matrix:
        repo:
          [
            tyk,
            tyk-analytics,
            tyk-pump,
            tyk-identity-broker,
            tyk-sink,
            portal,
            tyk-pro,
          ]
        include:
          - owner: TykTechnologies

    steps:
      - name: checkout ${{matrix.repo}}/${{matrix.branch}}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
        with:
          repository: ${{ matrix.owner }}/${{ matrix.repo }}
          ref: ${{ matrix.branch }}
          token: ${{ secrets.ORG_GH_TOKEN }}
          path: ${{ matrix.repo }}
          fetch-depth: 1

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4
        id: download
        with:
          name: binary-amd64

      - name: prepare gromit
        id: gromit
        run: |
          gromit="${{ steps.download.outputs.download-path }}/gromit"
          chmod +x $gromit
          echo "bin=${gromit}" >> "$GITHUB_OUTPUT"

      - name: update ${{ matrix.repo }}
        if: ${{ (github.event_name == 'push' && github.ref_name == 'master') || endsWith(github.head_ref, 'releng') }}
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
        run: |
          set -eo pipefail
          ${{ steps.gromit.outputs.bin }} policy sync ${{ matrix.repo }}
          echo "## :hospital: ℞ ${{ matrix.repo }}" >> $GITHUB_STEP_SUMMARY
          cd ${{ matrix.repo }} && for b in $(git for-each-ref --format '%(refname:short)' refs/heads); do
             echo -e "<details>\n <summary> ${{ matrix.repo }} $b </summary>\n"
             echo '```diff'
             git diff origin/${b} $b
             echo -e '```\n</details>'
          done | tee -a $GITHUB_STEP_SUMMARY
